#!C:\Users\90794\Desktop\学习\实习\航班归因分析\venv311\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
